#SPDX-License-Identifier: MIT-0
---
# tasks file for lujeni
- name: Include system tasks
  ansible.builtin.import_tasks: system.yaml

- name: Include neovim tasks
  ansible.builtin.import_tasks: neovim.yaml

- name: Include ghostty tasks
  ansible.builtin.import_tasks: ghostty.yaml

- name: Include i3 tasks
  ansible.builtin.import_tasks: i3.yaml
