#SPDX-License-Identifier: MIT-0
---
# handlers file for lujeni

- name: restart i3
  ansible.builtin.command: i3-msg restart
  become: yes
  become_user: "{{ user }}"
  listen: restart i3

- name: reload i3
  ansible.builtin.command: i3-msg reload
  become: yes
  become_user: "{{ user }}"
  listen: reload i3

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  listen: restart docker
